# escape=`
FROM plugins/base:windows-1909-amd64@sha256:fc1978bbe23e889dd7c5729cc8c44c2447a3ad00b539872167fe09ea43a136c7

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-github-release.exe C:/bin/drone-github-release.exe
ENTRYPOINT [ "C:\\bin\\drone-github-release.exe" ]
