# escape=`
FROM plugins/base:windows-1809-amd64@sha256:01bcfaa80edf10ef1dded7f1a79009c89a01852e4c9feb984b9b0bfe77f04ab2

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-github-release.exe C:/bin/drone-github-release.exe
ENTRYPOINT [ "C:\\bin\\drone-github-release.exe" ]
