# escape=`
FROM plugins/base:windows-1809-amd64@sha256:51b5a3280fbe76d9f0d26c9c02e4259927ca64ee05db4653b6073efa0155b6da

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-github-release.exe C:/bin/drone-github-release.exe
ENTRYPOINT [ "C:\\bin\\drone-github-release.exe" ]
