# escape=`
FROM plugins/base:windows-1809-amd64@sha256:bddee6de605caa974b429fc93d0da52eae0072d58578aa4b2722ae9b5d26345d

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-github-release.exe C:/bin/drone-github-release.exe
ENTRYPOINT [ "C:\\bin\\drone-github-release.exe" ]
