FROM plugins/base:multiarch@sha256:3511e8151bedc65bae396cd3e93ba6662a593c60262d4d29958e58b3c4b2eb4a

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/amd64/drone-github-release /bin/
ENTRYPOINT [ "/bin/drone-github-release" ]
