# escape=`
FROM plugins/base:windows-1909-amd64@sha256:e01f887e7a628ab7d7d57b6c8fd9495f5b8a19ea47e65b7939649be5ca7da49c

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone GitHub Release" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-github-release.exe C:/bin/drone-github-release.exe
ENTRYPOINT [ "C:\\bin\\drone-github-release.exe" ]
