FROM plugins/base:multiarch@sha256:4a865a7424ef5b41bb8ad8c7487025401d9894cf68bde28ced6b55dcc9b0623d

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone GitHub Release" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/amd64/drone-github-release /bin/
ENTRYPOINT [ "/bin/drone-github-release" ]
